language: cpp
dist: bionic
sudo: required
compiler: g++

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt-5.12.0-bionic -y
  - sudo apt update

install:
  - sudo wget https://dl.bintray.com/boostorg/release/1.65.0/source/boost_1_65_0.tar.gz
  - sudo tar zxf boost_1_65_0.tar.gz
  - cd boost_1_65_0/
  - sudo ./bootstrap.sh --prefix=/usr/local --with-libraries=system,thread,chrono,python,date_time,atomic
  - sudo ./b2 -d0
  - sudo ./b2 install -d0
  - cd ..
  - sudo apt install python-numpy
  - sudo apt install libblas-dev
  - sudo apt install liblapack-dev
  - sudo wget https://svwh.dl.sourceforge.net/project/arma/armadillo-9.900.1.tar.xz
  - sudo tar xf armadillo-9.900.1.tar.xz
  - cd armadillo-9.900.1/
  - cmake .
  - make
  - sudo make install
  - cd ..
  - sudo apt install mesa-common-dev libglu1-mesa-dev
  - sudo apt install qt512base
  - source /opt/qt512/bin/qt512-env.sh

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make