language: cpp
dist: bionic
sudo: required
compiler: g++

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt-5.12.0-bionic -y
  - sudo apt update

install:
  - sudo apt install libboost-all-dev
  - sudo apt install python-numpy
  - sudo apt install libblas-dev
  - sudo apt install liblapack-dev
  - sudo wget https://svwh.dl.sourceforge.net/project/arma/armadillo-9.900.1.tar.xz
  - sudo tar xf armadillo-9.900.1.tar.xz
  - cd armadillo-9.900.1/
  - cmake .
  - make
  - sudo make install
  - cd ..
  - sudo apt install mesa-common-dev libglu1-mesa-dev
  - sudo apt install qt512base
  - source /opt/qt512/bin/qt512-env.sh

before_script:
  - sudo unlink /usr/lib/x86_64-linux-gnu/libboost_python.so
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libboost_python-py36.so /usr/lib/x86_64-linux-gnu/libboost_python.so
  - sudo unlink /usr/lib/x86_64-linux-gnu/libboost_python.a
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libboost_python-py36.a /usr/lib/x86_64-linux-gnu/libboost_python.a
  - mkdir build
  - cd build
  - cmake ..

script:
  - make -j2 --trace