language: cpp
dist: bionic
sudo: required
compiler: g++

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt-5.12.0-bionic -y
  - sudo apt update

install:
  - sudo apt install qt512base
  - source /opt/qt512/bin/qt512-env.sh

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make